INFO     Utils.Base_init:Base_init.py:33 
exec cmd：iozone -r 512 -i 0 -i 1  -s 20G -I

WARNING  Utils.Base_init:Base_init.py:37 
None output

ERROR    Utils.Base_init:Base_init.py:39 
error：bash: 行 1: iozone: 未找到命令

WARNING  root:Base_init.py:57 测试数据未正常获取