{"name": "test_01", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <Case.test_fio.TestIOzone object at 0x0000026CED9BDE50>\n\n    def test_01(self):\n        fp.send('ls -l')\n>       assert False\nE       assert False\n\ntest_fio.py:10: AssertionError"}, "start": 1740022873632, "stop": 1740022874139, "uuid": "28169690-96ac-46a1-9d66-d4f6ec3e12e1", "historyId": "01a55d7010f48ebe0c3cf2503891f546", "testCaseId": "01a55d7010f48ebe0c3cf2503891f546", "fullName": "Case.test_fio.TestIOzone#test_01", "labels": [{"name": "parentSuite", "value": "Case"}, {"name": "suite", "value": "test_fio"}, {"name": "subSuite", "value": "TestIOzone"}, {"name": "host", "value": "Meiyi-EXT"}, {"name": "thread", "value": "1728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Case.test_fio"}]}